### PR TITLE
Setup dc_relay_domains not only for simple relays

### PR DESCRIPTION
**Pull request by zzzsochi**
Good morning!
I need to configure ``dc_relay_domains`` with SES for work with k8s.

### CODE REVIEW

**Comment by odino** [comment]
Hi @zzzsochi, thanks a bunch!

**Comment by zzzsochi** [comment]
Can you update the image on docker hub? Maybe set up automatic builds?

**Comment by odino** [comment]
Very strange as we already have automated builds on master :-S

Anyhow, just triggered a new manual build, you should be able to pull a new `latest` soon.

**Comment by zzzsochi** [comment]
Thanks!

**Pull request merged**
